### ISSUE TITLE
Knop contact formulier misschien niet duidelijk als je erop tabt.

### ISSUE THREAD

**Issue by DaanCarst** [sannevanseeventer/FDND-FinalSpatwater#32]
Als je door de website heen tabt en komt op de knop van het contact formulier lijkt het niet echt heel duidelijk dat je nu op de knop staat.

**Comment by zenitba** [comment]
Focus State Toegpast
<img width="949" alt="Schermafbeelding 2024-01-24 om 12 52 26" src="https://github.com/sannevanseeventer/FDND-FinalSpatwater/assets/112856019/8cf24687-0199-40be-821f-acf5b7c28704">

```css
 textarea:focus,
    input:focus {
        outline-color: var(--green);
        outline-width: 2px;
    }

    .no-border:focus {
        outline: 2px solid var(--darkblue);
        outline-offset: 4px;
    }
```
