### ISSUE TITLE
Misschien de hover activeren op de team kaarten als je erop tabt.

### ISSUE THREAD

**Issue by DaanCarst** [sannevanseeventer/FDND-FinalSpatwater#33]
je zou kunnen kijken of je deze kan activeren als je er mat tab op komt op de website.

**Comment by zenitba** [comment]
**Toegepast Focus State**
<img width="909" alt="Schermafbeelding 2024-01-24 om 12 50 36" src="https://github.com/sannevanseeventer/FDND-FinalSpatwater/assets/112856019/dc97ac92-1ee3-4ac9-ba24-baefb247e015">
```html
tabindex="0"
```


```css
 .card-item:focus {
    outline: 2px solid var(--darkblue);
    outline-offset: 4px;
  }
```
